using System;
using System.Collections.Generic;
using System.Text;

namespace Spotopedia.Data.Models.Enumerations
{
    public enum PostType
    {
        AutogeneratedSpotPost = 1,
        AutogeneratedChallengeEntryPost = 2,
    }
}
