namespace Spotopedia.Services.Data
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.EntityFrameworkCore;
    using NetTopologySuite.Geometries;
    using Spotopedia.Data.Common.Repositories;
    using Spotopedia.Data.Models;
    using Spotopedia.Data.Models.Enumerations;
    using Spotopedia.Services.Mapping;
    using Spotopedia.Web.ViewModels.Posts;
    using Spotopedia.Web.ViewModels.Spots;

    public class SpotsService : ISpotsService
    {
        private readonly IDeletableEntityRepository<Spot> spotsRepository;
        private readonly IDeletableEntityRepository<Address> spotAddressRepository;
        private readonly ICloudinaryService cloudinaryService;
        private readonly IPostsService postsService;
        private int lastAddedSpotId;

        public SpotsService(
            IDeletableEntityRepository<Spot> spotsRepository,
            IDeletableEntityRepository<Address> addressRepository,
            ICloudinaryService cloudinaryService,
            IRepository<SpotVote> spotVoteRepository,
            IPostsService postsService)
        {
            this.spotsRepository = spotsRepository;
            this.spotAddressRepository = addressRepository;
            this.cloudinaryService = cloudinaryService;
            this.postsService = postsService;
        }

        public async Task CreateAsync(CreateSpotInputModel input, string userId)
        {
            var imageUrls = new List<string>();
            foreach (var image in input.Images)
            {
                await using var memoryStream = new MemoryStream();
                await image.CopyToAsync(memoryStream);
                var destinationData = memoryStream.ToArray();

                try
                {
                    var imageUrl = await this.cloudinaryService.UploadPictureAsync(destinationData, image.FileName, "SpotsImages", 900, 600);
                    imageUrls.Add(imageUrl);
                }
                catch
                {
                }
            }

            var spot = new Spot
            {
                Title = input.Title,
                AddedByUserId = userId,
                Description = input.Description,
                Type = input.Type,
                KickOutLevel = input.KickOutLevel,
                Address = new Address
                {
                    AddressName = input.Address.AddressName,
                    Latitude = input.Address.Latitude,
                    Longitude = input.Address.Longitude,
                },
            };

            foreach (var imageUrl in imageUrls)
            {
                spot.SpotImages.Add(new SpotImage
                {
                    ImageUrl = imageUrl,
                    AddedByUserId = userId,
                });
            }

            await this.spotsRepository.AddAsync(spot);
            await this.spotsRepository.SaveChangesAsync();

            this.lastAddedSpotId = spot.Id;
        }

        public int GetLastAddedSpotId()
        {
            return this.lastAddedSpotId;
        }

        public IEnumerable<T> GetAllApproved<T>(int id, int itemsPerPage = 12)
        {
            return this.spotsRepository.AllAsNoTracking()
                .Where(x => x.IsApproved == true)
                .OrderByDescending(x => x.CreatedOn)
                .Skip((id - 1) * itemsPerPage)
                .Take(itemsPerPage)
                .To<T>()
                .ToList();
        }

        public IEnumerable<T> GetAllApproved<T>()
        {
            return this.spotsRepository.AllAsNoTracking()
                .Where(x => x.IsApproved == true)
                .OrderByDescending(x => x.CreatedOn)
                .To<T>()
                .ToList();
        }

        public IEnumerable<T> GetAllNotApproved<T>()
        {
            return this.spotsRepository.AllAsNoTracking()
                .Where(x => x.IsApproved == false)
                .To<T>()
                .ToList();
        }

        public async Task ApproveSpotAsync(int id, string approvedByUsername)
        {
            var spot = this.spotsRepository.All()
                .Include(x => x.SpotImages)
                .Include(x => x.AddedByUser)
                .FirstOrDefault(x => x.Id == id);

            spot.IsApproved = true;
            spot.ApprovedByUsername = approvedByUsername;
            spot.ApprovedOn = DateTime.UtcNow;
            this.spotsRepository.Update(spot);
            await this.spotsRepository.SaveChangesAsync();

            var postInputModel = new CreateAutoGeneratedPostInputModel
            {
                Content = spot.Title,
                SpotImages = spot.SpotImages,
                AddedByUserFirstName = spot.AddedByUser.FirstName,
                AddedByUserLastName = spot.AddedByUser.FirstName,
                Type = PostType.AutogeneratedSpotPost,
                SpotId = spot.Id,
            };

            await this.postsService.CreateAutoGeneratedAsync(postInputModel, spot.AddedByUserId);
        }

        public int GetSpotsCount()
        {
            return this.spotsRepository.AllAsNoTracking().Count();
        }

        public T GetById<T>(int id)
        {
            var spot = this.spotsRepository.AllAsNoTracking()
                                .Where(x => x.Id == id)
                                .To<T>()
                                .FirstOrDefault();
            return spot;
        }

        public async Task EditAsync(int id, string userId, EditSpotInputModel input)
        {
            var spot = this.spotsRepository.All().FirstOrDefault(x => x.Id == id);
            var address = this.spotAddressRepository.All().FirstOrDefault(x => x.SpotId == id);

            spot.Title = input.Title;
            spot.Description = input.Description;
            spot.Type = input.Type;
            spot.KickOutLevel = input.KickOutLevel;

            address.AddressName = input.Address.AddressName;
            address.Latitude = input.Address.Latitude;
            address.Longitude = input.Address.Longitude;

            var imageUrls = new List<string>();
            foreach (var image in input.Images)
            {
                await using var memoryStream = new MemoryStream();
                await image.CopyToAsync(memoryStream);
                var destinationData = memoryStream.ToArray();

                try
                {
                    var imageUrl = await this.cloudinaryService.UploadPictureAsync(destinationData, image.FileName, "SpotsImages", 900, 600);
                    imageUrls.Add(imageUrl);
                }
                catch
                {
                }
            }

            foreach (var imageUrl in imageUrls.Where(x => x != null))
            {
                spot.SpotImages.Add(new SpotImage()
                {
                    ImageUrl = imageUrl,
                    AddedByUserId = userId,
                    SpotId = id,
                });
            }

            this.spotsRepository.Update(spot);
            await this.spotsRepository.SaveChangesAsync();
        }

        public bool IsThisUserAddedThisSpot(string userId, int spotId)
        {
            return this.spotsRepository.All().Any(x => x.Id == spotId && x.AddedByUserId == userId);
        }

        public IEnumerable<KeyValuePair<string, string>> GetAllSpotsAsKeyValuePairs()
        {
            return this.spotsRepository.AllAsNoTracking().Select(x => new
            {
                x.Id,
                x.Title,
            }).ToList().Select(x => new KeyValuePair<string, string>(x.Id.ToString(), x.Title));
        }

        public IEnumerable<T> AllSpotsByUser<T>(string userId)
        {
            var spots = this.spotsRepository.All()
                .Where(x => x.AddedByUserId == userId && x.IsApproved == true)
                .OrderByDescending(x => x.CreatedOn)
                .To<T>()
                .ToList();

            return spots;
        }

        public IEnumerable<T> AllSpotsLikedByUser<T>(string id)
        {
            var spots = this.spotsRepository.All()
                .Where(x => x.SpotVotes.Any(x => x.AddedByUserId == id && x.Value == VoteType.Like) && x.IsApproved == true)
                .To<T>()
                .ToList();

            return spots;
        }

        public IEnumerable<SpotInListViewModel> GetNearBySpots(SingleSpotViewModel spotViewModel)
        {
            var allSpots = this.GetAllApproved<SpotInListViewModel>();

            var isValidLongitude = double.TryParse(spotViewModel.Address.Longitude, NumberStyles.Any, CultureInfo.InvariantCulture, out double longitude);
            var isValidLatitude = double.TryParse(spotViewModel.Address.Latitude, NumberStyles.Any, CultureInfo.InvariantCulture, out double latitude);

            var currentCoordinates = new Coordinate(longitude, latitude);

            var currentLocation = new Point(currentCoordinates)
            {
                SRID = 4326,
            };

            double radiusMeters = 1;

            var nearBySpots = new List<SpotInListViewModel>();

            foreach (var spot in allSpots)
            {
                if (spot.Id == spotViewModel.Id)
                {
                    continue;
                }

                var isValidLon = double.TryParse(spot.Address.Longitude, NumberStyles.Any, CultureInfo.InvariantCulture, out double lon);
                var isValidLat = double.TryParse(spot.Address.Latitude, NumberStyles.Any, CultureInfo.InvariantCulture, out double lat);

                var coordinates = new Coordinate(lon, lat);

                var location = new Point(coordinates)
                {
                    SRID = 4326,
                };

                if (location.Distance(currentLocation) <= radiusMeters)
                {
                    nearBySpots.Add(spot);
                }
            }

            return nearBySpots;
        }

        public async Task DeleteAsync(int id)
        {
            var spot = this.spotsRepository.All()
                .FirstOrDefault(x => x.Id == id);

            this.spotsRepository.Delete(spot);
            await this.spotsRepository.SaveChangesAsync();
        }

        public IEnumerable<T> GetAllReportedSpots<T>()
        {
            return this.spotsRepository.AllAsNoTracking()
                .Where(x => x.Reports.Any())
                .To<T>()
                .ToList();
        }
    }
}
